# Generated by Django 5.2.1 on 2025-05-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mymodel_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='image1',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
